-- Cloudflare D1 schema for cloud-ai-chat
-- Initialize:
--   local:  wrangler d1 execute cloud-ai-chat --local  --file=./schema.sql
--   remote: wrangler d1 execute cloud-ai-chat --remote --file=./schema.sql

CREATE TABLE IF NOT EXISTS chats (
  id         TEXT    PRIMARY KEY,          -- chat id (generated by the frontend via crypto.randomUUID())
  title      TEXT    NOT NULL DEFAULT '新对话',
  settings   TEXT,                          -- JSON blob of per-chat ChatSettings; NULL means defaults
  created_at INTEGER NOT NULL,             -- epoch milliseconds
  updated_at INTEGER NOT NULL              -- epoch milliseconds, used to sort the chat list
);

CREATE TABLE IF NOT EXISTS messages (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id    TEXT    NOT NULL,
  role       TEXT    NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
  content    TEXT    NOT NULL,
  reasoning  TEXT,                          -- assistant thinking chain; NULL for user/system messages
  created_at INTEGER NOT NULL,
  FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);

-- Sort the chat list by most recent activity.
CREATE INDEX IF NOT EXISTS idx_chats_updated_at ON chats (updated_at DESC);
-- Fetch history messages in order within a chat.
CREATE INDEX IF NOT EXISTS idx_messages_chat_id ON messages (chat_id, id);

-- ---------------------------------------------------------------------------
-- Migration for databases created before per-chat settings / reasoning existed.
-- D1 has no migration runner and CREATE TABLE IF NOT EXISTS will not alter an
-- existing table, so run the two statements below ONCE per existing database
-- (local and remote). A re-run fails with "duplicate column name", which is safe
-- to ignore.
--
--   ALTER TABLE chats    ADD COLUMN settings  TEXT;
--   ALTER TABLE messages ADD COLUMN reasoning TEXT;
-- ---------------------------------------------------------------------------
