-- Cloudflare D1 schema for cloud-ai-chat
-- Initialize:
--   local:  wrangler d1 execute cloud-ai-chat --local  --file=./schema.sql
--   remote: wrangler d1 execute cloud-ai-chat --remote --file=./schema.sql

CREATE TABLE IF NOT EXISTS chats (
  id         TEXT    PRIMARY KEY,          -- chat id (generated by the frontend via crypto.randomUUID())
  title      TEXT    NOT NULL DEFAULT '新对话',
  created_at INTEGER NOT NULL,             -- epoch milliseconds
  updated_at INTEGER NOT NULL              -- epoch milliseconds, used to sort the chat list
);

CREATE TABLE IF NOT EXISTS messages (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id    TEXT    NOT NULL,
  role       TEXT    NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
  content    TEXT    NOT NULL,
  created_at INTEGER NOT NULL,
  FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);

-- Sort the chat list by most recent activity.
CREATE INDEX IF NOT EXISTS idx_chats_updated_at ON chats (updated_at DESC);
-- Fetch history messages in order within a chat.
CREATE INDEX IF NOT EXISTS idx_messages_chat_id ON messages (chat_id, id);
